# Generated by Django 3.2.6 on 2022-01-01 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_auto_20211231_1935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='textf',
        ),
    ]
