# Generated by Django 3.2.6 on 2022-01-01 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0003_rename_text_post_textf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='textf',
            new_name='text',
        ),
    ]
